template:
  - switch:
    - turn_on:
      - data_template:
          entity_id: switch.gazon
          duration: '{{ states(''input_number.irrigation_gazonduration'') | int }}'
        action: rainbird.start_irrigation
      turn_off:
      - data:
          entity_id: switch.potager
        action: switch.turn_off
      default_entity_id: switch.irrig_gazon
      name: Gazon
      state: '{{ is_state(''switch.gazon'', ''on'') }}'
  - switch:
    - turn_on:
      - data_template:
          entity_id: switch.potager
          duration: '{{ states(''input_number.irrigation_potagerduration'') | int }}'
        action: rainbird.start_irrigation
      turn_off:
      - data:
          entity_id: switch.gazon
        action: switch.turn_off
      default_entity_id: switch.irrig_potager
      name: Potager
      state: '{{ is_state(''switch.potager'', ''on'') }}'
  - switch:
    - turn_on:
      - data_template:
          entity_id: switch.fraisiers_cave_a_vin
          duration: '{{ states(''input_number.irrigation_cavefraiseduration'') | int
            }}'
        action: rainbird.start_irrigation
      turn_off:
      - data:
          entity_id: switch.gazon
        action: switch.turn_off
      default_entity_id: switch.irrig_cavefraise
      name: Cave à vin / Fraisiers
      state: '{{ is_state(''switch.fraisiers_cave_a_vin'', ''on'') }}'

input_number:
  irrigation_rainthreshold:
    name: Threshold
    unit_of_measurement: hours
    initial: 2
    min: 1
    max: 12
    step: 1

  irrigation_interval:
    name: Intervalle
    unit_of_measurement: days
    initial: 1
    min: 0
    max: 7
    step: 1

  irrigation_gazonduration:
    name: Durée
    unit_of_measurement: minutes
    initial: 15
    min: 0
    max: 60
    step: 5

  irrigation_potagerduration:
    name: Durée
    unit_of_measurement: minutes
    initial: 30
    min: 0
    max: 60
    step: 5

  irrigation_cavefraiseduration:
    name: Durée
    unit_of_measurement: minutes
    initial: 15
    min: 0
    max: 60
    step: 5

input_datetime:
  irrigation_lastwatered:
    name: Dernier arrosage
    has_date: true
    has_time: true

automation:
  - alias: Irrigation.Irrigate
    trigger:
    - at: 08:00:00
      platform: time
    condition:
    - condition: template
      value_template: '{{ states("sensor.history_rainy_past_two_days") | int < states(''input_number.irrigation_rainthreshold'') | int }}'
    - condition: template
      value_template: '{{ states("sensor.irrig_days_since_last_irrigation") | int >= states(''input_number.irrigation_interval'') | int }}'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: script.rainbird_irrigate

  - alias: Irrigation.Gazon.ON
    trigger:
      platform: state
      entity_id: switch.irrig_gazon
      from: "off"
      to: "on"
    action:
      - service: timer.start
        data_template:
          entity_id: timer.irrigation_timer
          duration: "{{ states('input_number.irrigation_gazonduration') }}"

  - alias: Irrigation.Potager.ON
    trigger:
      platform: state
      entity_id: switch.irrig_potager
      from: "off"
      to: "on"
    action:
      - service: timer.start
        data_template:
          entity_id: timer.irrigation_timer
          duration: "{{ states('input_number.irrigation_potagerduration') }}"

  - alias: Irrigation.CaveFraise.ON
    trigger:
      platform: state
      entity_id: switch.irrig_cavefraise
      from: "off"
      to: "on"
    action:
      - service: timer.start
        data_template:
          entity_id: timer.irrigation_timer
          duration: "{{ states('input_number.irrigation_cavefraiseduration') }}"

script:
  rainbird_irrigate:
    alias: Arrosage
    sequence:
      - data: {}
        entity_id: switch.irrig_gazon
        service: switch.turn_on
      - delay: 00:00:59
      - wait_template: '{{ is_state(''switch.irrig_gazon'',''off'') }}'
      - data: {}
        entity_id: switch.irrig_potager
        service: switch.turn_on
      - delay: 00:00:59
      - wait_template: '{{ is_state(''switch.irrig_potager'',''off'') }}'
      - data: {}
        entity_id: switch.irrig_cavefraise
        service: switch.turn_on
      - delay: 00:00:59
      - wait_template: '{{ is_state(''switch.irrig_cavefraise'',''off'') }}'
      - service: input_datetime.set_datetime
        entity_id: input_datetime.irrigation_lastwatered
        data_template:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  
  rainbird_irrigate_off:
    alias: Arrosage Off
    sequence:
      - data: {}
        entity_id: script.rainbird_irrigate  
        service: script.turn_off
      - data: {}
        entity_id: switch.irrig_gazon
        service: switch.turn_off
      - data: {}
        entity_id: switch.irrig_potager
        service: switch.turn_off
      - data: {}
        entity_id: switch.irrig_cavefraise
        service: switch.turn_off

timer:
  irrigation_timer:        