homeassistant:
  customize:
    cover.volet_fenetre_cuisine:
      friendly_name: Fenêtre cuisine
    cover.volet_porte_cuisine:
      friendly_name: Porte cuisine
    cover.volet_salon_droite:
      friendly_name: Salon droite
    cover.volet_salon_gauche:
      friendly_name: Salon gauche
    cover.volet_salle_a_manger:
      friendly_name: Salle à manger
    cover.volet_chambre_parents:
      friendly_name: Chambre parents
    cover.volet_chambre_d_amis:
      friendly_name: Chambre d'amis
    cover.volet_bureau:
      friendly_name: Bureau
    cover.volet_chambre_romain:
      friendly_name: Chambre Romain
    cover.volet_chambre_valentine:
      friendly_name: Chambre Valentine

cover:
  - platform: group
    name: Tous les volets
    entities:
      - cover.volet_fenetre_cuisine
      - cover.volet_porte_cuisine
      - cover.volet_salon_droite
      - cover.volet_salon_gauche
      - cover.volet_salle_a_manger
      - cover.volet_chambre_parents
      - cover.volet_chambre_d_amis
      - cover.volet_bureau
      - cover.volet_chambre_romain
      - cover.volet_chambre_valentine
  - platform: group
    name: Etage
    entities:
      - cover.volet_fenetre_cuisine
      - cover.volet_porte_cuisine
      - cover.volet_salon_droite
      - cover.volet_salon_gauche
      - cover.volet_salle_a_manger
      - cover.volet_chambre_parents
      - cover.volet_chambre_d_amis
      - cover.volet_bureau
  - platform: group
    name: Soir
    entities:
      - cover.volet_salle_a_manger
      - cover.volet_chambre_parents
      - cover.volet_chambre_d_amis
      - cover.volet_bureau
      - cover.volet_chambre_romain
      - cover.volet_chambre_valentine
  - platform: group
    name: Cuisine
    entities:
      - cover.volet_fenetre_cuisine
      - cover.volet_porte_cuisine
  - platform: group
    name: Salon
    entities:
      - cover.volet_salon_droite
      - cover.volet_salon_gauche
  - platform: group
    name: Chambres bas
    entities:
      - cover.volet_chambre_romain
      - cover.volet_chambre_valentine
  - platform: group
    name: Pièces
    entities:
      - cover.volet_chambre_romain
      - cover.volet_chambre_valentine
      - cover.volet_chambre_parents
      - cover.volet_chambre_d_amis
      - cover.volet_bureau
  - platform: group
    name: Loft
    entities:
      - cover.volet_salon_droite
      - cover.volet_salon_gauche
      - cover.volet_fenetre_cuisine
      - cover.volet_porte_cuisine
      - cover.volet_salle_a_manger

sensor: 
  - platform: template
    sensors:
      sunelevation:
        friendly_name: "Elevation du soleil"
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      sunazimuth:
        friendly_name: "Azimut du soleil"
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"

binary_sensor:
  - platform: threshold
    name: "Soleil : Ouest"
    upper: 300
    lower: 250
    entity_id: sensor.sunazimuth
  - platform: threshold
    name: "Soleil : Sud"
    upper: 250
    lower: 120
    entity_id: sensor.sunazimuth
  - platform: threshold
    name: "Soleil : Est"
    upper: 150
    lower: 40
    entity_id: sensor.sunazimuth
  - platform: template
    sensors:
      vr_sun_hot:
        device_class: heat
        delay_on: 
          seconds: 300
        delay_off:
          seconds: 300
        value_template: "{{state_attr('weather.anse', 'temperature')|float(0) >= states('input_number.vr_sun_hot') |float(0)
                        and states('sensor.anse_cloud_cover')|float(0) <= states('input_number.vr_cloud_cover')|float(0) }}" 
        friendly_name: "Alerte haute température"
        #Math.round(weather.anse.attributes.forecast[0].temperature).toString()

input_number:
  vr_sun_hot:
    name: Seuil haute température
    min: 10
    max: 40
    step: 1
    unit_of_measurement: "°"
    icon: mdi:sun-thermometer-outline
  vr_cloud_cover:
    name: Seuil couverture nuageuse
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "%"
    icon: mdi:cloud-lock-outline 