sensor:
  - platform: rest
    resource: "https://mealie.utower.fr:9000/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal
    headers:
      Authorization: !secret mealie_token
    value_template: "{{ value_json[0].recipe.name }}"
    force_update: true
    scan_interval: 30

  - platform: rest
    resource: "https://mealie.utower.fr:9000/api/groups/mealplans/today"
    method: GET
    name: Mealie todays meal ID
    headers:
      Authorization: !secret mealie_token
    value_template: "{{ value_json[0].recipe.id }}"
    force_update: true
    scan_interval: 30
