automation:
  - alias: Allumage ampli hifi
    description: "Allume l'ampli quand il y a de la musique lancée dans le salon + set volume"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - media_player.salon
        to: playing
    action:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ampli
      - service: media_player.join
        data:
          group_members:
            - media_player.cuisine
        target:
          entity_id: media_player.salon
      - service: media_player.volume_set
        data:
          volume_level: 0.1
        target:
          entity_id: media_player.cuisine
      - service: media_player.volume_set
        data:
          volume_level: 0.7
        target:
          entity_id: media_player.salon
  - alias: Extinction ampli hifi
    description: "Extinction ampli hifi après 2 minutes d'inactivité"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - media_player.salon
        to: idle
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - media_player.salon
        to: "off"
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - media_player.salon
        to: paused
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - media_player.salon
        to: standby
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - media_player.salon
        to: unavailable
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - media_player.salon
        to: unknown
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ampli
