sensor:
  - platform: template
    sensors:
      unraid_free_space:
        friendly_name: Stockage 12TB
        unit_of_measurement: "%"
        value_template: "{{ (100-(states('sensor.192_168_1_127_mnt_disk1_free')|float(0) + states('sensor.192_168_1_127_mnt_disk2_free')|float(0) + states('sensor.192_168_1_127_mnt_disk3_free')|float(0) ) /12 /1000 * 100)|round(2) }}"

  - platform: plex_recently_added
    name: Derniers films
    token: !secret plex_token
    host: !secret unraid_ip
    port: 32400
    image_resolution: 300
    section_types:
      - movie

  - platform: plex_recently_added
    name: Derniers épisodes
    token: !secret plex_token
    host: !secret unraid_ip
    port: 32400
    image_resolution: 300
    section_types:
      - show

  - platform: plex_recently_added
    name: Derniers ajouts
    token: !secret plex_token
    host: !secret unraid_ip
    port: 32400
    image_resolution: 300
    max: 8
