homeassistant:
  customize:
    person.thomas:
      entity_picture: /local/thomas.jpg
    person.benedicte:
      entity_picture: /local/benedicte.jpg

template:
  - binary_sensor:
    - name: home_occupied
      unique_id: home_occupied
      device_class: occupancy
      state: "{{is_state('person.thomas', 'home') or is_state('person.benedicte', 'home')}}" 

proximity:
  distance_thomas_home:
    zone: home
    devices:
      - person.thomas
    tolerance: 50
    unit_of_measurement: m

  distance_benedicte_home:
    zone: home
    devices:
      - person.benedicte
    tolerance: 50
    unit_of_measurement: m 

group:
  parents:
    name: Parents
    entities:
      - person.benedicte
      - person.thomas