sensor:
  - platform: template
    sensors:
      piscine_salt_round:
        friendly_name: Sel
        unit_of_measurement: g/L
        value_template: "{{ (states('sensor.piscine_salt')|float(0) / 1000) | round(2) }}"
      piscine_last_update:
        friendly_name: Dernière mise à jour
        unit_of_measurement: min
        value_template: >-
          {{ ((as_timestamp(strptime(states('sensor.date_time'), "%Y-%m-%d, %H:%M")) - as_timestamp(states.sensor.piscine_temperature.last_changed)) / 60) | round() }}
