sensor:
  - platform: rest
    name: Dernière version Home Assistant
    resource: https://api.github.com/repos/home-assistant/core/releases/latest
    value_template: "{{ value_json.tag_name }}"
    scan_interval: 3600

template:
  - binary_sensor:
    - name: Mise à jour Home Assistant disponible
      state: >
        {{ states('sensor.home_assistant_versions') !=
            states('sensor.derniere_version_home_assistant') }}            